Fixing build system for Apache NetBeans IDE
Move module-java to /org/threeten/extra

Unfortunately now the build breaks with:

-------------------------------------------------------------
COMPILATION ERROR :
-------------------------------------------------------------
error: option --module-path not allowed with target 1.8